version: '3'
services:
  redis-broker:
    image: redis:latest
    container_name: redis-broker
    restart: always
    command: redis-server --appendonly yes
    environment:
      # - REDIS_PASSWORD=secret
      - REDIS_MAXMEMORY=1gb
      # - REDIS_MAXMEMORY_POLICY=allkeys-lru
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    networks:
      - redis-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
volumes:
  redis-data:
networks:
  redis-network: